### ISSUE TITLE
The subscription form doesn't appear anywhere

### ISSUE THREAD

**Issue by heizac** [FutureProcessing/glpi-webhook#1] opened 2021-12-10 14:55 UTC
Maybe I added the plugin in a wrong way (cuz there's /glpi/plugins/ and /glpi/files/_plugins i'm not sure where it should go, since there are plugin's folders in both these places) but I couldn't find the subscription form. The fpwebhook folder's permissions are the same as the other folders.

Something that I find strange is that a tab with the plugin's name was added in the Self-Service profile and not in the Super-Admin profile.
When I go to the tab Plugins > FP Webhook I can see this:
![Screenshot1](https://user-images.githubusercontent.com/36311842/145590767-953ab899-7f55-4c50-83a6-4ef4865279ba.png)
I have no idea what I can do with this index.

And when I go to the configuration page of the plugin in the Super-Admin profile it only shows this:
![Screenshot 2021-12-10 at 11-35-25 GLPI - TITLE](https://user-images.githubusercontent.com/36311842/145591450-2a0f5ad9-e3e3-434b-aa11-dbdf18fed647.png)

Self-Service tabs:
![Screenshot from 2021-12-10 11-43-24](https://user-images.githubusercontent.com/36311842/145592203-685a118d-9fcd-4f79-921f-7d163a68a857.png)
Super-Admin tabs:
![Screenshot from 2021-12-10 11-41-53](https://user-images.githubusercontent.com/36311842/145592272-f97db908-9c99-4ccd-86e4-dafb9e02bffc.png)

**Comment by mikron-ia** [comment] 2021-12-10 19:32
The plugin directory should go only into the `plugins/` directory. Please remove the `files/_plugins/` copy.

The first image you posted is the configuration page and this is the correct behavior. As for the subscription list, after activating the plugin, you should be seeing this in menu (as the Super-Admin):

![image](https://user-images.githubusercontent.com/9341377/145630857-7cc70db2-64ff-4ec2-a6af-560eb4fec8d2.png)

If you do, the `Webhook subscriptions` position will lead you to the list of subscriptions. You can also try to access the list manually under `[your GLPI host address]/plugins/fpwebhook/front/subscription.php`.

If you don't see that link, please provide more details on your installation (first and foremost, please list other plugins you have installed, since plugins are known to interfere with each other and sometimes break because of that) so this issue can be debugged.

**Comment by heizac** [comment] 2021-12-13 11:58
Ok, I removed the copy from `files/_plugins/` and left it only at `plugins/`

I get it that the index page should appear like that, but shouldn't it be somewhere else? I mean, the Self-Service profile can see that just clicking on Plugin and then FP Webhook, as you can see in the third image of my first post (Self-Service tabs). 
It doesn't make sense to me that any of that should appear on the Self-Service profile, but that's one thing, the other and more important is that I can't see the subscription page anywhere.

I tried to access manually, as Super-Admin:  (and also, that's the other plugins I have. Do they all have the right permissions? I wonder if the owner and group should be `www-data` instead of `root`)
![Screenshot from 2021-12-13 08-30-34](https://user-images.githubusercontent.com/36311842/145806376-de7db4fe-3259-4007-ae95-8f14fd66f31c.png)

The way I installed fpwebhook was simply downloading the plugin, unziping it and moving it to the `/plugins` folder. Then I enabled it at GLPI. 

I think I'm gonna remove it all and try again from scratch. I'm kinda new to GLPI, so there's a lot of things I don't know how they should behave.

**Comment by mikron-ia** [comment] 2021-12-17 21:12
Since I am unable to reproduce the issue, I reworked the piece that might be the possible reason. Please test the `installation-fix` branch from #2, it may fix the issue.

**Comment by heizac** [comment] 2021-12-20 14:23
Ok, now I can see that page, but there's no `Save` button so I couldn't manage to save anything. And it doesn't appear to be saving anything just by getting out of the page. Am I missing something here or a button is really missing?

![Screenshot from 2021-12-20 11-13-21](https://user-images.githubusercontent.com/36311842/146781695-daffbd00-cf3d-4bf9-8d72-4a3b155f5f67.png)

**Comment by mikron-ia** [comment] 2021-12-20 15:04
Thank you for the verification! As for the button, exiting w/o saving does not save anything and this is the intended appearance:
![image](https://user-images.githubusercontent.com/9341377/146787766-9dbae90f-48c7-4fd3-9801-03b8e475a981.png)
so you should be seeing the `Add` button. Investigation on this is in progress.

**Comment by mikron-ia** [comment] 2021-12-21 12:34
Since the missing button is a separate issue from the subscription list & form availability, I'm closing this issue since the availability issue is resolved. The problem should no longer exist in the next minor release.

**Closed by mikron-ia** 2021-12-21 12:34 UTC
